upis/tehnicka/urls.py
from django.urls import path

from django.urls import path
from . import views
# we could say: from application import views as application_view and use it as application_view.details

app_name = 'tehnicka'
urlpatterns = [
    path("",views.index_base,name="index_base"),
    path("add-student/", views.dodajucenika, name='dodajucenika'),
    path("smjer/<int:smjer_id>", views.index, name='index'),
    path("details/<int:ucenik_id>", views.details, name='details'),
    path("delete/<int:ucenik_id>", views.delete, name='delete'),
    path("pretrazivanje/<int:smjer_id>", views.pretraga, name='pretragaucenika'),
    path("popuni/",views.popuniBazu,name="popunibazu"),
    path("pdf/<int:smjer_id>",views.get_pdf,name='get_pdf'),
   
]

upis/upis/urls.py
# Uncomment next two lines to enable admin:
from django.contrib import admin
from django.urls import path,include
from users import views

urlpatterns = [
    path("", views.index,name="index"),
    path('admin/', admin.site.urls),
    path('tscze/',include("tehnicka.urls")),
    path("login/", include("users.urls"))
]

upis/users/urls.py
  
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
#    path("ucenici", views.ucenici_view, name="ucenici"),
]

upis/tehnicka/models.py
from django.db import models
import datetime
# Create your models here.


class Smjer(models.Model):
    naziv_smjera=models.CharField(max_length=60)
    
    class Meta:
        verbose_name_plural='Smjerovi'

    def __str__(self):
        return self.naziv_smjera

def current_year():
    return datetime.date.today().year

def year_choices():
    return [(r,r) for r in range(1984, datetime.date.today().year+1)]

class Skola(models.Model):
    ime_skole=models.CharField(max_length=60)

    class Meta:
        verbose_name_plural='Skole'
    def __str__(self):
        return self.ime_skole
       

class Ucenik(models.Model): 
    ime=models.CharField(max_length=60)
    prezime=models.CharField(max_length=60)
    godina_upisa=models.IntegerField(default=current_year)
    smjer=models.ManyToManyField(Smjer)
    skola_id=models.ForeignKey(Skola, on_delete=models.CASCADE )
    ukupno_bodova=models.FloatField(default='0')

    class Meta:
        verbose_name_plural = "Učenici"

    def __str__(self):
        return  f"{self.ime} {self.prezime}" 

class Takmicenje(models.Model):
    vrsta_takmicenja=models.CharField(max_length=40)
    class Meta:
        verbose_name_plural = "Takmicenja"

    def __str__(self):
        return self.vrsta_takmicenja

class Priznanja(models.Model):
    naziv_priznanja=models.CharField(max_length=40)
    bodovi=models.IntegerField(default='0')
  
    ucenik_id=models.ManyToManyField(Ucenik)
    class Meta:
        verbose_name_plural = "Priznanja"

    def __str__(self):
        return f"id:{self.id}:{self.naziv_priznanja}-{self.bodovi}"


class Predmet(models.Model):
    naziv_predmeta=models.CharField(max_length=60)
    
    #Prosljeduje se ManyToMany veza u novu tabelu Predmet_Ocjene
    ocjene_ucenika=models.ManyToManyField(Ucenik, through='Predmet_Ocjena')
    class Meta:
        verbose_name_plural = "Predmeti"

    def __str__(self):
        return f"{self.naziv_predmeta}"

class Predmet_Ocjena(models.Model):
    ucenik=models.ForeignKey(Ucenik, on_delete=models.CASCADE)
    predmet=models.ForeignKey(Predmet, on_delete=models.CASCADE)
    ocjena=models.IntegerField(default='0')
    razred=models.IntegerField(default='6')

    class Meta:
        verbose_name_plural = "Ocjene iz predmeta"

    def __str__(self):
        return f"{self.ucenik.ime}_{self.ucenik.prezime}_{self.predmet.naziv_predmeta}_{self.ocjena}_{self.razred}"

class Kljucni_Predmeti(models.Model):
    naziv_pr=models.CharField(max_length=40)
    smjer=models.ManyToManyField(Smjer)

class Razred(models.Model):
    naziv_razreda=models.CharField(max_length=50)
    broj_razreda=models.IntegerField(default='6')
    predmet=models.ManyToManyField(Predmet)

upis/users/models.py
from django.db import models

# Create your models here.

upis/tehnicka/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import  Predmet,Ucenik,Predmet_Ocjena,Priznanja,Smjer,Skola
from django.contrib.auth import authenticate, login, logout
from django.template.loader import get_template, render_to_string


import json
from .createUcenik import *
from .statistika import *
from .updateUcenik import *
from .deleteUcenik import *
from .pdf_statistika import *
from .pretragaUcenika import *
from .seeds import *


#------------------ INDEX BASE --------------------------#
def index_base(request):
   
    context={
    'smjerovi': Smjer.objects.all()
    }
    return render(request, 'tehnicka/index_base.html',context)

def index_viev_predmet(request):
    predmeti=Predmet.objects.all()
    context={
        'predmeti':predmeti
        }
    return render(request,'tehnicka/dodajUcenika.html',context)

#----------------- POPUNJAVANJE BAZE PODACIMA ZA TEST --------------------------#

def popuniBazu(request):
    dodajSmjerove(request)
    dodajKljucnePredmete(request)
    dodajPredmete(request)
    dodajSkole(request)
    return HttpResponse("Baza popunjena")
# Create your views here.
def index(request,smjer_id):
    message=''
    if request.session.get('message'):
        message='Korisnik obrisan!'
        del request.session['message']
    return racunajStatistiku(request, smjer_id, message)
#----------------------DODAJ UCENIKA -----------------------------------#

def dodajucenika(request):
        if request.method == "POST":
            try:
                #predmet_razred9_ocjena=request.POST.getlist('razred9')
                #predmeti_razred7_ocjena=request.POST.getlist('razred7')
                #context={
                    #'ocjene':predmet_razred9_ocjena
                   # }
                #return render(request,'tehnicka/dodajUcenika.html',context)
                saveStudent(request)
                response=redirect('/tscze/')
                return response
            except KeyError:
               
                return HttpResponse(" Error dodajucenika")
        else: # GET request
           
            return getStudent(request)

#------------ DETAILS UPDATE UCENIK -----------------------#
def details(request, ucenik_id):
    if request.method == "POST":
        try:
            return updateStudent(request, ucenik_id)
        except KeyError:
            return HttpResponse("Key error - post uredi")

    else:
        return get_for_update(request, ucenik_id)


#----------- DELETE UCENIK -----------------------------#
def delete(request, ucenik_id):

    if request.user.is_authenticated:
        return deleteStudent(request, ucenik_id)



#-------- RENDER TO PDF ---------------------#
#class HtmlPdf(FPDF, HTMLMixin):
    #pass


#def print_pdf(request):    
    #pdf = HtmlPdf()
    #pdf.add_page()
    #pdf.write_html(render_to_string('tehnicka/index.html'))

    #response = HttpResponse(pdf.output(dest='S').encode('latin-1'))
    #response['Content-Type'] = 'application/pdf'

   # return response
def get_pdf(request,smjer_id):
       return pdf_racunajStatistiku(request,smjer_id)


#---------------------- PRETRAGA UCENIKA ------------------------------------#

def pretraga(request,smjer_id):
    if request.method=="POST":
        return pretragaUcenika(request,smjer_id)

upis/users/views.py
  
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from tehnicka.models import Ucenik, Smjer, Predmet

# Create your views here.

def index(request):
    if not request.user.is_authenticated:
        return render(request, "users/login.html", {"message": None})
    context = {
        "user": request.user
    }
    #return HttpResponse(request.user.username)
    return render(request, "users/user.html", context)

def login_view(request):
    username = request.POST["username"]
    password = request.POST["password"]
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "users/login.html", {"message": "Invalid credentials."})

def logout_view(request):
    logout(request)
    return render(request, "users/login.html", {"message": "Logged out."})

upis/tehnicka/templates/tehnicka/base.html
<!DOCTYPE html>
<html>
    <head>
      <meta charset="UTF-8">
      <title>
        {%block title%}
          HI
        {% endblock %}
      </title>
        

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <!-- <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"> -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
    <body>

      <div class="container">
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tehnicka:index_base' %}"> Home</a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">

            {% if request.user.is_authenticated %}
            <li class="nav-item"> <a class="nav-link" href="{% url 'tehnicka:index_base' %}"> Lista ucenika</a> </li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'tehnicka:dodajucenika' %}"> Dodaj ucenika</a> </li>
            <li class="nav-item"> <a class="nav-link" href="#"> Logout</a> </li>
            {% else %}
            <li class="nav-item"> <a class="nav-link" href="#"> Login</a> </li>
            {% endif %}
          </ul>
        </nav>
           
      </div>
        {% block body %}
        {% endblock %}
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
          {% load static %}
        <script type="text/javascript" src="{% static 'tehnicka/anel_js.js' %}"></script>
        <!-- glyphicons not working
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
       -->
    </body>
</html>

upis/tehnicka/templates/tehnicka/index.html
{% extends "tehnicka/base.html" %}

{% block title%}
  Home
{% endblock %}

{% block body %}
  {% if message %}
  <div class="container">
    <p class="help-block">
          {{ message }}
    </p>

    </div>
  {% endif %}
  <div class="container">
    <h4 style="text-align:center">  Spisak ucenika {{ br1  }} {{br2}}</h4>
    <hr>
      <!-- SEARCH BAR-->
      <form action="{% url 'tehnicka:pretragaucenika' smjer.id %}" method="post">
          {% csrf_token %}
          <div class="p-1 bg-light rounded rounded-pill shadow-sm mb-4">
            <div class="input-group">
              <input type="search" placeholder="What're you searching for?" aria-describedby="button-addon1" class="form-control border-0 bg-light" name="search">
              <div class="input-group-append">
                <button id="button-addon1" type="submit" class="btn btn-link text-primary"><i class="fa fa-search"></i></button>
              </div>
            </div>
          </div>
       </form>
 
      <div class="table-responsive" id="tbl_svi_ucenici">
        <table class="table table-sm table-hover table-bordered">
          <thead>
            <tr>
              <th  class="table-info" scope="col" rowspan="2">#</th>
              <th  class="table-info" scope="col" rowspan="3">Ime</th>
              <th  class="table-info" scope="col" rowspan="3">Prezime</th>
              <th  class="table-info" scope="col" rowspan="3" colspan="5" ><strong>I Opci kriterij </strong>
              <br> <em> Uspjeh VI-IX razreda o.s </em></th>
              <th  class="table-info" scope="col" rowspan="3" colspan="7" ><strong> II Posebni kriterij</strong>
              <br> <em> Relevantni nastavni predmeti </em></th>
              <th  class="table-info" scope="col" rowspan="3" colspan="3" ><strong>III Opci kriterij</strong>
              <br> <em> Uspjeh VI-IX razreda o.s</em></th>
              <th  class="table-danger" scope="col" rowspan="3"colspan="1">Suma</th>
              {% if request.user.is_authenticated %}
                <th class="table-info" scope="col" rowspan="3"colspan="2"></th>
              {% endif %}
              <th  class="table-info" scope="col" rowspan="3">Osnovna skola</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th class="table-info" scope="col" rowspan="1"></th>
              <th class="table-info" scope="col" rowspan="1"></th>
              <th class="table-info" scope="col" rowspan="1"></th>
              <th class="table-info" scope="col" rowspan="1"></th>
              <th class="table-info" scope="col" rowspan="1"></th>
              <th class="table-info" scope="col" rowspan="1"></th>
              <th class="table-info" scope="col" rowspan="1"></th>
              <th class="table-info" scope="col" rowspan="1"></th>
            {% for predmet in kljucni_predmeti %}
              <th  class="table-info" scope="col" rowspan="1" colspan="2" >{{ predmet.naziv_pr }}</th>
                {% endfor %}
              

              <th  class="table-danger" scope="col" rowspan="2" colspan="1"> <center> Ukupno </center>  </th>
              <th class="table-info" scope="col" rowspan="1"></th>
              <th class="table-info" scope="col" rowspan="1"></th>
              <th class="table-info" scope="col" rowspan="1"></th>
              <th class="table-danger" scope="col" rowspan="1"></th>
              {% if request.user.is_authenticated %}
                <th class="table-info" scope="col" rowspan="3"colspan="2"></th>
              {% endif %}
              <th class="table-info" scope="col" rowspan="1"></th>
            </tr>

            <tr>
              <th class="table-info" scope="col" rowspan="1"></th>
              <th class="table-info" scope="col" rowspan="1"></th>
              <th class="table-info" scope="col" rowspan="1"></th>
              <th class="table-info" scope="col" rowspan="1"> VI </th>
              <th class="table-info" scope="col" rowspan="1"> VII </th>
              <th class="table-info" scope="col" rowspan="1"> VIII </th>
              <th class="table-info" scope="col" rowspan="1"> IX </th>
              <th class="table-danger" scope="col" rowspan="1"> <center> Ukupno </center> </th>

              <th class="table-info" scope="col" rowspan="1"> VIII </th>
              <th class="table-info" scope="col" rowspan="1"> IX </th>
              <th class="table-info" scope="col" rowspan="1"> VIII </th>
              <th class="table-info" scope="col" rowspan="1"> IX </th>
              <th class="table-info" scope="col" rowspan="1"> VI </th>
              <th class="table-info" scope="col" rowspan="1"> VII </th>

              <th class="table-info" scope="col" rowspan="1">O</th>
              <th class="table-info" scope="col" rowspan="1">K</th>
              <th class="table-info" scope="col" rowspan="1">F</th>
              <th class="table-danger" scope="col" rowspan="1"></th>
              <th class="table-info" scope="col" rowspan="1"></th>
            </tr>
            <!-- DATA -->
            <tr>
              {% for ucenik in ucenici %}
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ ucenik.ime }}</td>
                <td>{{ ucenik.prezime }}</td>
                <!-- // I prosjek ocjena 6-9 -->
                {% for key, value in prosjek_6.items %}
                  {% if key == ucenik.id %}
                  <td>{{ value }}</td>
                  {% endif %}
                {% endfor%}

                {% for key, value in prosjek_7.items %}
                  {% if key == ucenik.id %}
                  <td>{{ value }}</td>
                  {% endif %}
                {% endfor%}

                {% for key, value in prosjek_8.items %}
                  {% if key == ucenik.id %}
                  <td>{{ value }}</td>
                  {% endif %}
                {% endfor%}

                {% for key, value in prosjek_9.items %}
                  {% if key == ucenik.id %}
                  <td>{{ value }}</td>
                  {% endif %}
                {% endfor%}

                <!-- // I prosjek ocjena ukupno -->
                {% for key, value in prosjek_ukupno.items %}
                  {% if key == ucenik.id %}
                  <td class="table-danger">{{ value }}</td>
                  {% endif %}
                {% endfor%}

                <!-- // II posebni predmeti po smjerovima-->
                {% for key, value in posebni_predmet_1_ocjena_razred8.items %}
                  {% if key == ucenik.id %}
                  <td>{{ value }}</td>
                  {% endif %}
                {% endfor%}
                {% for key, value in posebni_predmet_1_ocjena_razred9.items %}
                  {% if key == ucenik.id %}
                  <td>{{ value }}</td>
                  {% endif %}
                {% endfor%}
                {% for key, value in posebni_predmet_2_ocjena_razred8.items %}
                  {% if key == ucenik.id %}
                  <td>{{ value }}</td>
                  {% endif %}
                {% endfor%}
                {% for key, value in posebni_predmet_2_ocjena_razred9.items %}
                  {% if key == ucenik.id %}
                  <td>{{ value }}</td>
                  {% endif %}
                {% endfor%}
                {% for key, value in posebni_predmet_3_ocjena_razred6.items %}
                  {% if key == ucenik.id %}
                  <td>{{ value }}</td>
                  {% endif %}
                {% endfor%}
                {% for key, value in posebni_predmet_3_ocjena_razred7.items %}
                  {% if key == ucenik.id %}
                  <td>{{ value }}</td>
                  {% endif %}
                {% endfor%}

                <!-- // II posebni predmeti po smjerovima ukupno-->
                {% for key, value in posebni_predmet_ukupno.items %}
                  {% if key == ucenik.id %}
                  <td class="table-danger">{{ value }}</td>
                  {% endif %}
                {% endfor%}

                <!-- // III -->
                {% for key, value in priznanje_opcinsko.items %}
                  {% if key == ucenik.id %}
                  <td>{{ value }}</td>
                  {% endif %}
                {% endfor%}

                {% for key, value in priznanje_kantonalno.items  %}
                  {% if key == ucenik.id %}
                  <td>{{ value }}</td>
                  {% endif %}
                {% endfor%}

                {% for key, value in  priznanje_federalno.items %}
                  {% if key == ucenik.id %}
                  <td>{{ value }}</td>
                  {% endif %}
                {% endfor%}
                  <td>
                <!-- // SUMA I,II,III -->
                {% for key, value in  ukupno.items %}
                  {% if key == ucenik.id %}
                  <td class="table-danger" >{{ value }}</td>
                  {% endif %}
                {% endfor%}
                {% if request.user.is_authenticated %}
                  <td> <a href="{% url 'tehnicka:details' ucenik.id %} "> <span> Uredi </span><i class="fa fa-user"></i> </a> </td>
                  <td> <a href="{% url 'tehnicka:delete' ucenik.id %} "> <span> Da </span><i class="fa fa-user-times"></i> </a> </td>
                  
                {% endif %}
                <td>{{ ucenik.skola_id.ime_skole }}</td>

              </tr>
              {% endfor%}
               
          </tbody>
        </table>
          {% if request.user.is_authenticated %}
         <button type="button" class="btn btn-outline-primary "><a href="{% url 'tehnicka:get_pdf' smjer.id %}"<span>Izradi PDF</span></a></button>
          {% endif %}
      </div>

    </div>

    <br>
    <br>
    <hr>



{% endblock %}

upis/tehnicka/templates/tehnicka/index_base.html
{% extends "tehnicka/base.html" %}
{%block title%}
  Spisak ucenika -svi
{% endblock %}
  <div class="container">
    <h4 style="text-align:center">  Spisak ucenika </h4>
    <div class="jumbotron">
      <h1> Upis ucenika u prvi razred 2019/2020</h1>
      <h3> Tehnicka skola Zenica </h3>
      <h3> 2019/2020 </h3>
    </div>
  </div>
{% block body %}
  <div class="container">
    {% for smjer in smjerovi%}
    {% if smjer.naziv_smjera == "Racunarska tehnika i automatika" %}
      <a href="{% url 'tehnicka:index' smjer.id %}"> <span> {{smjer.naziv_smjera}} </span><i class="fa fa-bolt"></i> </a>
    {% endif %}
    {% if smjer.naziv_smjera == "Elektronicar" %}
      <a href="{% url 'tehnicka:index' smjer.id %}"> <span> {{smjer.naziv_smjera}} </span><i class="fa fa-microchip"></i> </a>
    {% endif %}
    {% if smjer.naziv_smjera == "Masinski tehnicar" %}
      <a href="{% url 'tehnicka:index' smjer.id %}"> <span> {{smjer.naziv_smjera}} </span><i class="fa fa-building"></i> </a>
    {% endif %}
    {% if smjer.naziv_smjera == "Tehnicar drumskog saobracaja" %}
      <a href="{% url 'tehnicka:index' smjer.id %}"> <span> {{smjer.naziv_smjera}} </span><i class="fa fa-industry"></i> </a>
    {% endif %}
    {% if smjer.naziv_smjera == "Arhitektonski tehnicar" %}
      <a href="{% url 'tehnicka:index' smjer.id %}"> <span> {{smjer.naziv_smjera}} </span><i class="fa fa-flask"></i> </a>
    {% endif %}
    <br>
    {% endfor %}
  </div>
{% endblock %}

upis/users/templates/users/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>
          {% block title%}
          {% endblock %}
        </title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </head>
    <body>
      <div class="container">
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
          <ul class="navbar-nav ml-auto">

            {% if request.user.is_authenticated %}
            <li class="nav-item"> <a class="nav-link" href="{% url 'tehnicka:index_base' %}"> Lista ucenika</a> </li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'tehnicka:dodajucenika' %}"> Dodaj ucenika</a> </li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'logout' %}"> Logout</a> </li>
            {% else %}
            <li class="nav-item"> <a class="nav-link" href="{% url 'index' %}"> Login</a> </li>
            {% endif %}
          </ul>
        </nav>

      </div>
        {% block body %}
        {% endblock %}
    </body>
</html>

upis/users/templates/users/login.html
{% extends "users/base.html" %}
{% block title%}
  Login
{% endblock %}
{% block body %}

<div class="container">
  <h1 style="text-align:center">Login</h1>
  {% if message %}
      <p style="text-align:center" class="help-block">
          {{ message }}
      </p>
  {% endif %}
  <div class="container">
    <div class="row">
      <div style="width:30%; margin:0 auto;">
        <form action="{% url 'login' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="username"> Username: </label>
              <input id="username" class="form-control" name="username" type="text" placeholder="User name"/>
            </div>
            <div class="form-group">
              <label for="pass">Password: </label>
              <input id="pass" class="form-control" name="password" type="password" placeholder="Password"/>
            </div>
            <button class="btn btn-secondary" type="submit" name="button"> Login </button>
            <!-- <input class="btn btn-default" type="submit" value="Login"/> -->
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

upis/users/templates/users/user.html
{% extends "users/base.html" %}
{% block title %}
  Zdravo {{ user.username}}
{% endblock %}


{% block body %}
<div class="container">

  <div class="jumbotron">
    <h1> Upis ucenika u prvi razred 2019/2020</h1>
    <h3> Tehnicka skola Zenica </h3>
  </div>
  <div class="continaer">
      <h1>Zdravo {{ user.username }}</h1>

    <p class="help-block">
      Pristupite unosu novog ucenika.
    </p>
  </div>
  <hr>

</div>
{% endblock %}